version: '3.8'

services:
  couchbase:
    image: couchbase:enterprise-7.0.1
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 8095:8095
      - 11210:11210
    volumes:
      - couchbase-tms:/opt/couchbase/var

volumes:
  couchbase-tms:

# docker network create localdev --subnet 10.0.1.0/24
networks:
  default:
    name: localdev
