#!/usr/bin/env bash

export PGPASSWORD=password

echo === BALANCES ===

query='psql -q -h localhost -U postgres -d postgres --csv -t -c '

echo -n "Total:            "
$query "SELECT SUM((content->>'balance')::integer) FROM balances"

echo -n "Pending trans.:   "
$query "SELECT SUM(json_array_length(content->'pending')) FROM balances"

echo -n "Processed trans.: "
$query "SELECT SUM(json_array_length(content->'processed')) FROM balances"

echo
echo === OUTBOX ===

echo -n "Sent:     "
$query "SELECT COUNT(*) FROM outbox WHERE sent = true"

echo -n "Unsent:   "
$query "SELECT COUNT(*) FROM outbox WHERE sent IS NULL"

echo
echo === SAGAS ===

echo -n "Completed:    "
$query "SELECT COUNT(*) FROM sagas where content->'stage'->>'type' = 'completed'"

echo -n "Rolled back:  "
$query "SELECT COUNT(*) FROM sagas where content->'stage'->>'type' = 'rolled-back'"

echo -n "In progress:  "
$query "SELECT COUNT(*) FROM sagas where content->'stage'->>'type' = 'in-progress'"
