#!/usr/bin/env bash

echo -n "Total balance:   "
cbq -u Administrator -p password -s "$(cat <<CQL
SELECT SUM(balance) as totalBalance
FROM sagas._default.balances
CQL
)" | tail -n+7 | jq '.results[].totalBalance'

echo -n "Total pending:   "
cbq -u Administrator -p password -s "$(cat <<CQL
SELECT SUM(ARRAY_LENGTH(pending)) as totalPending
FROM sagas._default.balances
CQL
)" | tail -n+7 | jq '.results[].totalPending'

echo -n "Total outbox:    "
cbq -u Administrator -p password -s "$(cat <<CQL
SELECT COUNT(META().id) as totalOutbox
FROM sagas._default.outbox
CQL
)" | tail -n+7 | jq '.results[].totalOutbox'

echo -n "Total processed: "
cbq -u Administrator -p password -s "$(cat <<CQL
SELECT SUM(ARRAY_LENGTH(processed)) totalProcessed
FROM sagas._default.balances s
CQL
)" | tail -n+7 | jq '.results[].totalProcessed'

echo

cbq -u Administrator -p password -s "$(cat <<CQL
SELECT META().id, pending
FROM sagas
WHERE META().id LIKE "balance::%"
AND pending
LIMIT 10
CQL
)" | tail -n+10 | jq '.results'

